port:  5000
markdown: kramdown
name: "Indivisible Tacoma"
url: http://reps.indivisibletacoma.org
encoding: utf-8
timezone: America/Los_Angeles
description: "Enter your address to find and contact your federal, state, county and local elected representatives"
gems:
  - jekyll-redirect-from
google_api_key: AIzaSyClA5qbarnOkp2kDJDml9L0rzEg5N4YfUU
include: [CNAME]
